Repository hbarton2/cscd350-f24-TeamNull, pull requests merged in 2024-10, with the labels that each got.

#69 Feature/shane task add field
  .idea/google-java-format.xml
  .idea/misc.xml
  src/main/java/proj/TeamNull/UMLdevkit/EntryPoint.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/Menu/MenuAlpha.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLClassBackup.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLComponent.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLComponentManager.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLComponentManagerBackup.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLField.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLMethod.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLParameter.java
  src/main/java/proj/TeamNull/UMLdevkit/reference/UMLComponent/UMLRelationship.java
  src/test/java/proj/TeamNull/UMLdevkkit/UMLComponentTests/UMLClassTest.java
  src/test/java/proj/TeamNull/UMLdevkkit/UMLComponentTests/UMLFieldTest.java
  src/test/java/proj/TeamNull/UMLdevkkit/UMLComponentTests/UMLMethodTest.java
  src/test/java/proj/TeamNull/UMLdevkkit/UMLComponentTests/UMLParameterTest.java
  src/test/java/proj/TeamNull/UMLdevkkit/UMLComponentTests/UMLRelationshipTest.java
Labels: documentation, enhancement

#73 Foundation; added Colton's classes
  src/main/java/module-info.java
  src/main/java/proj/TeamNull/UMLdevkit/EntryPoint.java
  src/main/java/proj/TeamNull/UMLdevkit/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/UMLMethod.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/ActionHandler.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Commands.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Display.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Parser.java
  src/test/java/proj/TeamNull/UMLdevkit/ParserTest.java
Labels: help wanted

#85 Hackthon
  JUNK/NOTUSED/DeleteUMLClass.java
  JUNK/NOTUSED/RenameUMLClass.java
  JUNK/NOTUSED/UMLClass.java
  JUNK/NOTUSED/UMLClassRelationship.java
  JUNK/NOTUSED/UMLField.java
  JUNK/NOTUSED/UMLMethod.java
  JUNK/reference/Utility/GeneralCommandAction.java
  src/main/java/module-info.java
  src/main/java/proj/TeamNull/UMLdevkit/EntryPoint.java
  src/main/java/proj/TeamNull/UMLdevkit/UMLClassRelationship.java
  src/main/java/proj/TeamNull/UMLdevkit/UMLField.java
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLRelationshipType.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/ActionHandler.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandAction.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandFactory.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Commands.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/DeleteUMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Display.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Parser.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/ParsingInputs.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/RenameUMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Storage.java
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
  src/test/java/proj/TeamNull/UMLdevkit/ParserTest.java
  src/test/java/proj/TeamNull/UMLdevkit/UMLClassRelationshipTest.java
  src/test/resources/commands.json
Labels: enhancement

#89 v1.1.50 Welcome screen and help cmd added
  README.md
  src/main/java/module-info.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Commands.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Display.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Storage.java
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
Labels: enhancement

#91 v1.1.53 parameter now able to be optionally added
  README.md
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandFactory.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
Labels: enhancement

#93 v1.1.55 remove parameter now able to be optionally removed and remove method
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLRelationship.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandFactory.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
Labels: enhancement

#98 v1.1.59 save load and clear
  src/main/java/module-info.java
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandFactory.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Commands.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Storage.java
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
  src/main/resources/proj/TeamNull/UMLdevkit/hdd/testing
Labels: enhancement

#103 mavenTest
  .idea/.name
  .idea/misc.xml
  README.md
  dependency-reduced-pom.xml
  pom.xml
  pom.xml.versionsBackup
  src/main/java/module-info.java
  src/main/java/proj/TeamNull/UMLdevkit/uml/UMLClass.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/CommandFactory.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Commands.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Display.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Functions.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/ParsingInputs.java
  src/main/java/proj/TeamNull/UMLdevkit/utilities/Storage.java
  src/main/resources/commands.json
  src/main/resources/proj/TeamNull/UMLdevkit/commands.json
  src/main/resources/proj/TeamNull/UMLdevkit/hdd/GsonTest
  src/main/resources/proj/TeamNull/UMLdevkit/hdd/test3
Labels: enhancement, wontfix

#121 v2.2.70 Documentations Update including README
  README.md
  documentation/sprint1_uml_proposal.pdf
  documentation/sprint2_MVCRefrator_proposal.pdf
  src/main/java/umleditor/sprint1/utilities/Display.java
Labels: documentation
